Location finder 2
DTS-STN/Benefits-Finder pull request #79
Opened 2021-05-25 16:28 UTC by TishamIslam

# Description
BF-105 Investigate api/tool to determine province by IP

Added a call to the geolocation API on the index page and made it assume the location of the user if there is no location already given by the cookie. Also lets the user know that their location was assumed and asks them to confirm/modify the assumption (no implementation of that).

#Technical Details
The environment variable that I added (IP_LOCATION_API_URL) is the full url with the API key for the geolocation API that we are using. 
There is another API from the same geolocation site that needs no API key and returns the client's IP address, which is then sent to our serverside API to call the geolocation API. As the IP API call needs to be separate anyways, I moved it to its own separate function in case we need to use it for anything else. 

#Comments/To-dos
I'm not 100% sure about the unit tests that I've added as I'm new to jest, but basically I mocked return values for the api calls and made sure the functions to be tested responded accordingly. 
I'm also not too sure about whether the way I changed the select-picker's value is 100% appropriate, but I don't know how to do it using React states, though I suspect it might be simpler than expected.
The LocationAssumption component still needs to be styled and modified accordingly to our design mockups.

## Meets Definition of Done
- [x] Unit tests up to date
- [x] E2E tests up to date
- [x] I18n

2021-05-27 14:00 UTC, nibivi77 requested changes
Overall, I like your code, its clean! Here are some requests :) Let me or the team know if you have any questions. I will gladly help you out!

2021-05-27 15:19 UTC, DaceyTom2 requested changes
There are a few minor structure changes that can be made to improve the flow

2021-05-27 15:19 UTC, DaceyTom2 commented on pages/index.js
> +        document.getElementById("location-select").value = location;
We can probably set location based off the situation just set

2021-05-27 15:19 UTC, DaceyTom2 commented on pages/index.js
> +    getUserLocationAssumption()
Instead of setting the location assumption from index it would be easier when creating the cookie initially. Can we have a call to discuss options?

2021-05-27 15:41 UTC, TishamIslam commented on lib/assumptions.test.js
> +global.fetch = jest.fn();
I don't think the latter bit applies to my code, given that I didn't use the fetch-mock library. Just added the describe() things!

2021-05-27 15:41 UTC, TishamIslam commented on pages/index.js
> +        document.getElementById("location-select").value = location;
I think it is an issue on your end, perhaps because of Kyle's latest PR?

2021-05-31 12:52 UTC, DaceyTom2 requested changes
I believe lib/assumptions lib/ip and api/assumptions can be removed now

2021-06-02 14:47 UTC, closed without merging